### ISSUE TITLE
Page empty when loaded in editor

### ISSUE THREAD

**Issue by gabrielwalt** [Adobe-Marketing-Cloud/aem-sightly-repl#10]
When opening http://localhost:4502/editor.html/content/repl.html, only a blank window is displayed.

**Comment by chandrushiggaon** [comment]
Hi,
I am beginner in AEM, and planning to practice Sightly. I have Adobe Experience Manager 6+, ideally running on port 4504 and followed the instructions given in this link https://github.com/Adobe-Marketing-Cloud/aem-htl-repl to setup a live code editing environment for HTL templates. but upon opening http://localhost:4504/editor.html/content/repl.html i am getting blank page. 
Any help from this group members will be appreciated.

**Comment by vladbailescu** [comment]
@chandrushiggaon Are you sure you're installing the REPL package correctly (given that you're using a different port, the Maven command might fail if you didn't update the configured port)?

If in doubt, you can change the Package Manager or see if the REPL is loading at http://localhost:4504/content/repl.html

**Comment by chandrushiggaon** [comment]
@vladbailescu Thanks for the input. It worked. Need more suggestions from you and group on how to begin and excel in sightly.

**Comment by Sagar-Nachankar** [comment]
Hi,
I am updating a page and it is updating properly. I can see the versions of it from timeline. Thus, I have updated a page three times, but the issue is that whenever I am checking a page preview for old pages (old versions) I am getting only blank page.
Can you please suggest on it.
