### ISSUE TITLE
Update to content-package-maven plugin 0.0.24 to support latest maven / java versions

### ISSUE THREAD

**Issue by olaf-otto** [Adobe-Marketing-Cloud/aem-sightly-repl#12]
Currently, the packaging by the content package maven plugin may fail using java 1.8 + mvn 3.3.3:

```
[ERROR] Failed to execute goal com.day.jcr.vault:content-package-maven-plugin:0.0.20:package (default-package) on project com.adobe.granite.sightly.repl: Execution default-package of goal com.day.jcr.vault:content-package-maven-plugin:0.0.20:package failed: A required class was missing while executing com.day.jcr.vault:content-package-maven-plugin:0.0.20:package: org/slf4j/helpers/MarkerIgnoringBase
[ERROR] -----------------------------------------------------
[ERROR] realm =    extension>com.day.jcr.vault:content-package-maven-plugin:0.0.20
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/d:/repo/com/day/jcr/vault/content-package-maven-plugin/0.0.20/content-package-maven-plugin-0.0.20.jar
[ERROR] urls[1] = file:/d:/repo/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[2] = file:/d:/repo/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
[ERROR] urls[3] = file:/d:/repo/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[4] = file:/d:/repo/org/apache/maven/maven-archiver/2.3/maven-archiver-2.3.jar
[ERROR] urls[5] = file:/d:/repo/org/codehaus/plexus/plexus-archiver/1.0-alpha-9/plexus-archiver-1.0-alpha-9.jar
[ERROR] urls[6] = file:/d:/repo/org/codehaus/plexus/plexus-io/1.0-alpha-1/plexus-io-1.0-alpha-1.jar
[ERROR] urls[7] = file:/d:/repo/org/codehaus/plexus/plexus-utils/1.4.9/plexus-utils-1.4.9.jar
[ERROR] urls[8] = file:/d:/repo/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[9] = file:/d:/repo/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[10] = file:/d:/repo/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
[ERROR] urls[11] = file:/d:/repo/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar
[ERROR] urls[12] = file:/d:/repo/commons-codec/commons-codec/1.2/commons-codec-1.2.jar
[ERROR] urls[13] = file:/d:/repo/org/codehaus/mojo/animal-sniffer-maven-plugin/1.8/animal-sniffer-maven-plugin-1.8.jar
[ERROR] urls[14] = file:/d:/repo/org/codehaus/mojo/animal-sniffer/1.8/animal-sniffer-1.8.jar
[ERROR] urls[15] = file:/d:/repo/org/ow2/asm/asm-all/4.0/asm-all-4.0.jar
[ERROR] urls[16] = file:/d:/repo/org/codehaus/mojo/java-boot-classpath-detector/1.8/java-boot-classpath-detector-1.8.jar
[ERROR] urls[17] = file:/d:/repo/org/apache/maven/reporting/maven-reporting-api/2.0.1/maven-reporting-api-2.0.1.jar
[ERROR] urls[18] = file:/d:/repo/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-6/doxia-sink-api-1.0-alpha-6.jar
[ERROR] urls[19] = file:/d:/repo/commons-cli/commons-cli/1.0/commons-cli-1.0.jar
[ERROR] urls[20] = file:/d:/repo/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar
[ERROR] urls[21] = file:/d:/repo/org/apache/maven/shared/maven-common-artifact-filters/1.2/maven-common-artifact-filters-1.2.jar
[ERROR] urls[22] = file:/d:/repo/org/apache/maven/shared/maven-plugin-testing-harness/1.1/maven-plugin-testing-harness-1.1.jar
[ERROR] urls[23] = file:/d:/repo/org/apache/sling/org.apache.sling.commons.json/2.0.6/org.apache.sling.commons.json-2.0.6.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
```
This works, however, when using content-package-maven plugin 0.0.24. This currently is the latest version and should be configured explicitly IMO.

**Comment by hoangbienit** [comment]
Hi,
I am using plugin 0.0.24, but It doesn't work.
<plugin>
                        <groupId>com.day.jcr.vault</groupId>
                        <artifactId>content-package-maven-plugin</artifactId>
                        <version>0.0.24</version>

[ERROR] Failed to execute goal com.day.jcr.vault:content-package-maven-plugin:0.0.24:check-signature (default-check-signature) on project lyf-web.ui.apps: The plugin com.day.jcr.vault:content-package-maven-plugin:0.0.24 requires Maven version 3.1.0 -> [Help 1]

Please help me fix it.
Thanks,

**Comment by vladbailescu** [comment]
@hoangbienit, you need to upgrade to a newer Maven version.

**Comment by hoangbienit** [comment]
@vladbailescu 
I am using Apache maven 3.5.0
`mvn -v
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T02:39:06+07:00)`
The plugin com.day.jcr.vault:content-package-maven-plugin:0.0.24 requires Maven version 3.1.0

How to fix it?
Thank & regards,
Bien

**Comment by vladbailescu** [comment]
@hoangbienit, I just tested with Maven 3.5.0 (on both Java 7 and 8) and the project builds successfully.

The artifact mentioned in your error (`lyf-web.ui.apps`) seems like a dependency or module that you added/created. Can you check if you're able to build the current `master` branch without any other changes?

**Comment by aaerrolla** [comment]
in my case  I got this  same error , looks like this plugin   goal requires  running AEM.
after starting AEM and running   mvn -PautoInstallPackage install   solved the issue 

"org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.day.jcr.vault:content-package-maven-plugin:0.0.24:install (install-package) on project echo62.ui.apps: Connection refused (Connection refused)  "

**Comment by andicoaker** [comment]
I am getting a similar error as above, that @aaerrolla posted on Mar 2nd. 

"Failed to execute goal com.day.jcr.vault:content-package-maven-plugin:0.0.24:install (install-content-package) on project aem-www.ui.apps: Connection refused (Connection refused)"

**Comment by dfrusone** [comment]
> I am getting a similar error as above, that @aaerrolla posted on Mar 2nd.

"Failed to execute goal com.day.jcr.vault:content-package-maven-plugin:0.0.24:install (install-content-package) on project aem-www.ui.apps: Connection refused (Connection refused)"

This happens when your instance of AEM is not running

**Comment by yashduggal** [comment]
Hello @dfrusone 
i am getting the same error as you mentioned and even my instance is working but still this issue is coming again and again. 
ANY OTHER REASON ?

**Comment by tiagondelgado** [comment]
> > I am getting a similar error as above, that @aaerrolla posted on Mar 2nd.
> 
> "Failed to execute goal com.day.jcr.vault:content-package-maven-plugin:0.0.24:install (install-content-package) on project aem-www.ui.apps: Connection refused (Connection refused)"
> 
> This happens when your instance of AEM is not running

Resolve my problem

**Comment by dfrusone** [comment]
@yashduggal Try restart your running environment
