### ISSUE TITLE
Build fails with check signature, not in GZIP format

### ISSUE THREAD

**Issue by joannehoaz** [Adobe-Marketing-Cloud/aem-sightly-repl#8]
Running the command
mvn clean install content-package:install

produces the following error and no package is built:
Failed to execute goal com.day.jcr.vault:content-package-maven-plugin:0.0.20:check-signature (default-check-signature) on project com.adobe.granite.sightly.repl: Failed to check signatures: Not in GZIP format

Is there anything else to try?

**Comment by gabrielwalt** [comment]
Hi, I'm not sure what exactly is causing the problem you describe, but I've updated the installation instructions with a method that doesn't require Maven anymore. Have a look at https://github.com/Adobe-Marketing-Cloud/aem-sightly-repl.

**Comment by tlwhit2** [comment]
Thank you!

**Comment by Shivamurthy-MN** [comment]
Hi all,
How to make this work for all pages?

Thanks,
Shiv MN

**Comment by raducotescu** [comment]
I think that this was fixed as a side-effect of #12. I cannot reproduce this issue with a fresh build. Feel free to reopen it if that's still the case.
